version: '4'
services:

  jms:
    container_name: jms
    image: vromero/activemq-artemis
    restart: always
    environment:
      ARTEMIS_USERNAME: 'service-produto'
      ARTEMIS_PASSWORD: 'live'
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616
      - 8161

  produto:
    container_name: produto
    image: service-produto/produto:0.0.1-SNAPSHOT
    environment:
      JMS_HOST: jms
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - jms