version: '4'
services:

  jms:
    container_name: jms
    image: vromero/activemq-artemis
    restart: always
    environment:
      ARTEMIS_USERNAME: 'service-produto'
      ARTEMIS_PASSWORD: 'live'
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616
      - 8161

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml?ro
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    expose:
      - 3000
    ports:
      - 3000:3000