global:
  # How frequently to scrape targets by default.
  - scrape_interval: 15s
  - evaluation_interval: 15s

rule_files:

# A list of scrape configurations.
scrape_configs:
  # The job name assigned to scraped metrics by default.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'produtos'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:8080' ]